#!/usr/bin/env bash

offlineimap -u quiet -q -f INBOX -a martinmch & pid1=$!
offlineimap -u quiet -q -f INBOX -a christiansen & pid2=$!
offlineimap -u quiet -q -f INBOX -a ucph & pid3=$!
wait $pid1
wait $pid2
wait $pid3
