#!/usr/bin/env bash

case $1 in
    out) /home/martinmch/.bin/outgoing $2; exit 1;;
esac

mailMartinmch="$(find "/home/martinmch/mail/martinmch/INBOX/new/" -type f | wc -l)"

if [ "$#" -gt 0 ]; then
    echo "$mail"
    exit 1
fi

# Silence is golden
if [[ "$mail" -gt 0 ]]; then
    echo "$mailMartinmch new mail(s)"
fi
