#!/usr/bin/env bash

drive=$2

open() {
    sudo cryptsetup luksOpen $drive music
    sudo mount /dev/mapper/music $HOME/music/
}

close() {
    sudo umount $HOME/music/
    sudo cryptsetup luksClose /dev/mapper/music
}

case $1 in
    "open") open $drive;;
    "close") close $drive;;
    *) echo "Invalid option";;
esac
