#!/usr/bin/env bash
# In a folder with many files following the name convention
# lecture[[:digit:]]+.md
# the script will report if there are any gaps in the number sequence.

numberOfLectureFiles=$(ls -c1 \
    | grep lecture \
    | sed -e 's/lecture\([[:digit:]]\+\).md/\1/' \
    | sort -n \
    | wc -l)

numberOfLectures=$(ls -c1 \
    | grep lecture \
    | sed -e 's/lecture\([[:digit:]]\+\).md/\1/' \
    | sort -n \
    | tail -1)

if [ -z "$numberOfLectures" -o -z "$numberOfLectureFiles" ]
then
    exit 1
fi

if [ "$numberOfLectures" -ne "$numberOfLectureFiles" ]
then
    if [ -t 1 ]
    then
        missing=$(echo "$numberOfLectures"-${numberOfLectureFiles} | bc)
        echo "${missing} missing lecture(s)!"
        echo 
        for (( i = 1; i < "${numberOfLectures}"; i++ )); do
            name="lecture${i}.md"
            if [ ! -f "$name" ]
            then
                echo "$name"
            fi
        done
    else
        echo ${missing} 
    fi
fi
