#!/usr/bin/env bash

lastLectureNum=$(ls -c1 \
    | grep lecture \
    | sed -e 's/lecture\([[:digit:]]\+\).md/\1/' \
    | sort -n \
    | tail -1)

lectureNum=$(echo $lastLectureNum+1 | bc)
fileName=lecture${lectureNum}.md

cat<<< "---
title: Modul ${lectureNum} - 
author: martinmch
date: $(date +"%Y-%m-%d")
categories:
    - EG
    - 2gif1
    - 2gif5
tags:
    -
slug: 2gif-mod${lectureNum}
---

# " >> "$fileName"

if [ ! -t 1 ] ; then echo "$fileName"; fi
