#!/usr/bin/env bash

mails=$(echo `ls /home/martinmch/.msmtp/mailqueue | wc -l`/2 | bc)

# If any arguments has been supplied, the output should just be the
# number of unsent mails
# if [[ "$mails" > 0 ]]; then
#     aplay /home/martinmch/.bin/mailout.wav &> /dev/null &
# fi

if [ "$#" -gt 0 ]; then
    echo "$mails"
    exit 1
fi

if [[ "$mails" > 1 ]]; then
    core="<span color='red'>$mails unsent mails</span>"
    noun="them"
elif [[ "$mails" == 1 ]]; then
    core="one unsent mail"
    noun="it"
elif [[ "$mails" == 0 ]]; then
    exit 0
fi

echo -e You have "$core" in your outbox.
echo To send "$noun" type \`sendmail -r\`.
