#!/bin/sh

B='#00000033'  # blank
C='#ffffff88'  # clear ish
D='#336699cc'  # default
T='#2d5b89ee'  # text
W='#880000bb'  # wrong
V='#bb00bbbb'  # verifying

i3lock              \
--insidevercolor=$C   \
--ringvercolor=$V     \
--insidewrongcolor=$C \
--ringwrongcolor=$D   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--textcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--keyhlcolor=$W       \
--bshlcolor=$W        \
\
--screen 0            \
--blur 5              \
--clock               \
--indicator           \
--timestr="%H:%M"  \
--datestr="%A, %M %b %Y" \
--wrongtext="Access denied"  \
--veriftext="Verifying"  \
--textsize=20  \
# --modsize=10
# --timefont=comic-sans
# --datefont=monaco
# etc
